# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GgvVJ_v6y_-cxDgX5bvWxYpMDTaIOZr7
"""

import numpy as np
a = [5,6,7,8,9]
type(a)
y = np.array(a)
print(y)
np.max(a)
print(np.max(a))
np.min(a)
print(np.min(a))
np.mean(a)
print(np.mean(a))
np.median(np.median(a))

import numpy as np
w=np.random.randint(2,50,5)
print(w)

x=np.sort(w)
print(w)

import numpy as np
x = np.arange(1,26).reshape(5,5)
print(x)

